import { type NextPage } from 'next';
import Head from 'next/head';
import Form from './components/form';

import { api } from '~/utils/api';

const Home: NextPage = () => {
    const newLink = api.link.createLink.useQuery({ longLink: 'mbaydoun.com' });

    return (
        <>
            <Head>
                <title>Link Shortener</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]'>
                <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16 '>
                    <h1 className='text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]'>
                        Link{' '}
                        <span className='text-[hsl(280,100%,70%)]'>
                            Shortener
                        </span>
                    </h1>
                    <div className='grid grid-cols-1 gap-4 md:gap-8'>
                        <Form />
                    </div>
                    {newLink.data
                        ? `https://link-shortener-five.vercel.app/${newLink.data.newLink}`
                        : newLink.error?.message}
                </div>
            </main>
        </>
    );
};

export default Home;
